-- SQL to create the order_prefix table for Menha Boutique
-- Run this in your Supabase SQL Editor

-- 1. Create the table
CREATE TABLE IF NOT EXISTS public.order_prefix (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    prefix TEXT DEFAULT 'ORD' NOT NULL,
    next_sequence BIGINT DEFAULT 1000 NOT NULL
);

-- 2. Insert the initial configuration
INSERT INTO public.order_prefix (prefix, next_sequence)
VALUES ('ORD', 1000)
ON CONFLICT DO NOTHING;

-- 3. Enable RLS (Row Level Security)
ALTER TABLE public.order_prefix ENABLE ROW LEVEL SECURITY;

-- 4. Create policies (Allow reading and updating by the anon key for simplicity in this project)
-- NOTE: In a production app, you might want to restrict update to authenticated admins only.
CREATE POLICY "Allow public read access" ON public.order_prefix
    FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Allow public update access" ON public.order_prefix
    FOR UPDATE TO anon, authenticated USING (true);

-- 5. Grant permissions to the anon/authenticated roles
GRANT ALL ON public.order_prefix TO anon, authenticated, service_role;
